### ISSUE TITLE
Bug when using tsm with chalk 5.0.0

### ISSUE THREAD

**Issue by leondreamed** [lukeed/tsm#31]
First of all, thanks for this amazing project!

I noticed that tsm fails to import dependencies from chalk 5, giving the following error:

```
(node:41021) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41021) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
file:///Users/leonzalion/projects/tsm-bug/node_modules/.pnpm/chalk@5.0.0/node_modules/chalk/source/index.js#supports-color.mts:26
const { stdout: stdoutColor, stderr: stderrColor } = supportsColor;
                ^

TypeError: Cannot destructure property 'stdout' of 'supportsColor' as it is undefined.
    at file:///Users/leonzalion/projects/tsm-bug/node_modules/.pnpm/chalk@5.0.0/node_modules/chalk/source/index.js#supports-color.mts:26:17
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

It seems like the chalk `supportsColor` import is becoming `undefined`, and I believe it has something to do with how chalk imports its dependencies:
```typescript
import ansiStyles from '#ansi-styles';
import supportsColor from '#supports-color';
```

Here is a GitHub repo that reproduces this error: https://github.com/leonzalion/tsm-bug
Node version: 16.13.2

Let me know if this is a `tsm` bug and/or if there's a workaround to this issue!

**Comment by btakita** [comment]
Also getting this issue. I used a `package.json` `pnpm.override` to "chalk": "4.1.2" to work around this problem.

**Comment by BasixKOR** [comment]
It seems like tsm doesn't support [subpath imports](https://nodejs.org/api/packages.html#subpath-imports) yet?

**Comment by azat-io** [comment]
Same issue

**Comment by karlhorky** [comment]
Created a Replit for this here:

https://replit.com/@karlhorky/tsm-chalk-5-example#package.json

(this confirms that the problem is also present with `esbuild@0.14.54`)

**Comment by karlhorky** [comment]
Nice, `tsm@2.3.0` is working, thanks! 🙌

**Comment by azat-io** [comment]
Same error with tsm v2.3.0

```
(node:42830) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:42830) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
/Users/user/Developer/azat-io/node_modules/.pnpm/chalk@5.1.2/node_modules/chalk/source/index.js:8
const {stdout: stdoutColor, stderr: stderrColor} = supportsColor;
               ^


TypeError: Cannot destructure property 'stdout' of 'supportsColor' as it is undefined.
    at <anonymous> (/Users/user/Developer/azat-io/node_modules/.pnpm/chalk@5.1.2/node_modules/chalk/source/index.js:8:16)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.1.0
```
